### ISSUE TITLE
New pca version not producing expected graphs 

### ISSUE THREAD

**Issue by mersalas** [erdogant/pca#50]
pca v2.0.4 not producing the expected graphs and producing errors. See google colab: https://colab.research.google.com/drive/1UTets1alPB1tcA_wpKAKBd_14nENqoXX?usp=sharing
I tried solving this by installing different versions of matplotlib and python versions but to no avail.

**Comment by erdogant** [comment]
Thank you for notifying. This warning/error seem to occur because of a new version of matplotlib when fontsize is set to 0.
I update the code to prevent the warning/error. Can you try again? Also I updated the notebook. I noticed some old parameters.

update to the latest version with:

`pip install -U pca`

**Comment by mersalas** [comment]
Thank you for updating the library. What version of matplotlib did you use in your notebook? I still could not generate the same graphs. I am using matplotlib v3.7.2 in python 3.8.

**Comment by erdogant** [comment]
Have you tried to use the colab notebook over [here](https://erdogant.github.io/pca/pages/html/Documentation.html#colab-notebook)?

matplotlib.__version__
3.7.1
